
package view;

import usuarios.Cnpj;
import usuarios.dao.UsuariosDAO;

/**
 *
 * @author gusta
 */
public class AdicionarCli extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdicionarCli
     */
    public AdicionarCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCnpjUsuario = new javax.swing.JTextField();
        txtCnpjCadastro = new javax.swing.JTextField();
        butaoCadastroCli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Cnpj:");

        jLabel2.setText("Usuario:");

        txtCnpjUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjUsuarioActionPerformed(evt);
            }
        });

        txtCnpjCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjCadastroActionPerformed(evt);
            }
        });

        butaoCadastroCli.setText("Cadastrar");
        butaoCadastroCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoCadastroCliActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("INSIRA O ACESSO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCnpjCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtCnpjUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(butaoCadastroCli))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel4)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCnpjCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCnpjUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(butaoCadastroCli)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCnpjUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjUsuarioActionPerformed

    private void txtCnpjCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjCadastroActionPerformed

    private void butaoCadastroCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCadastroCliActionPerformed
        
        Cnpj c = new Cnpj();
        UsuariosDAO us = new UsuariosDAO();
        c.setCnpj(txtCnpjCadastro.getText());
        c.setUsuario(txtCnpjUsuario.getText());
        us.createSave(c);
        
        
    }//GEN-LAST:event_butaoCadastroCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butaoCadastroCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCnpjCadastro;
    private javax.swing.JTextField txtCnpjUsuario;
    // End of variables declaration//GEN-END:variables
}
